export const REPOSITORY_PORTS = {
  SUB_SCENARIO: 'ISubScenarioRepositoryPort',
  SCENARIO: 'IScenarioRepositoryPort',
  ACTIVITY_AREA: 'IActivityAreaRepositoryPort',
  FIELD_SURFACE: 'IFieldSurfaceTypeRepositoryPort',
  COMMUNE: 'ICommuneRepositoryPort',
  NEIGHBORHOOD: 'INeighborhoodRepositoryPort',
  USER: 'IUserRepositoryPort',
  CITY: 'ICityRepositoryPort',
  RESERVATION: 'IReservationRepositoryPort',
  RESERVATION_TIMESLOT: 'IReservationTimeslotRepositoryPort',
  RESERVATION_INSTANCE: 'IReservationInstanceRepositoryPort',
  TIME_SLOT: 'ITimeSlotRepositoryPort',
  RESERVATION_STATE: 'IReservationStateRepositoryPort',
  ROLE: 'IRoleRepositoryPort',
  SUB_SCENARIO_IMAGE: 'ISubScenarioImageRepositoryPort',
} as const;
